# Generated by Django 6.0.2 on 2026-02-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
